version: '3'
services:
  api:
    build:
      context: .
      dockerfile: "D:\\Work\\Training\\Backend\\Web API\\Tutorial_Fast\\Section3-APIDev\\DockerFile"
    ports:
      - 8000:8000
    entrypoint: sh -c "alembic upgrade head && uvicorn app.main_orm:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./:/usr/src/app:ro
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PWD=test
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=postgres
      - TOKEN_PWD=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE=30
    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=fastapi
      - POSTGRES_USER=postgres
    
    volumes:
      - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db: 
